/**
 * Bonus Engine
 * Handles direct referral bonus + 10-level commission distribution.
 *
 * Level Commission Matrix (configurable via DB settings):
 * Level 1: 5%, Level 2: 3%, Level 3: 2%, Level 4-10: 1% each
 */

const prisma = require('../lib/prisma')
// Default commission rates
const DEFAULT_RATES = {
  direct: 5.0, // Fixed 5% direct referral bonus
  levels: [0, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], // Level 1 is direct, Levels 2-15 handled here
}

async function getCommissionRates() {
  try {
    const [levelsSetting, directSetting] = await Promise.all([
      prisma.setting.findUnique({ where: { key: 'level_bonus_rates' } }),
      prisma.setting.findUnique({ where: { key: 'direct_bonus_pct' } })
    ])
    return {
      direct: directSetting ? parseFloat(directSetting.value) : DEFAULT_RATES.direct,
      levels: levelsSetting ? JSON.parse(levelsSetting.value) : DEFAULT_RATES.levels,
    }
  } catch {
    return DEFAULT_RATES
  }
}

/**
 * Credit a bonus to a user's income wallet and create ledger entry.
 * @param {PrismaClient} tx  - Transaction client
 * @param {number} userId
 * @param {number} amount
 * @param {string} bonusType - 'direct' | 'level' | 'trading'
 * @param {number} fromUserId
 * @param {number} level
 * @param {string} remarks
 */
async function creditBonus(tx, userId, amount, bonusType, fromUserId, level, remarks) {
  if (amount <= 0) return

  const updated = await tx.user.update({
    where: { id: userId },
    data:  { income_wallet_balance: { increment: amount } },
  })

  await Promise.all([
    tx.bonus.create({
      data: {
        user_id:      userId,
        from_user_id: fromUserId,
        type:         bonusType,
        level,
        amount,
      },
    }),
    tx.incomeLedger.create({
      data: {
        user_id:        userId,
        type:           'credit',
        amount,
        balance_after:  updated.income_wallet_balance,
        remarks,
        reference_type: 'bonus',
      },
    }),
  ])
}

/**
 * Trigger direct referral bonus (5%) when a member activates a trade package.
 * The 15-level bonus has been moved to daily ROI matching.
 *
 * @param {number} memberId   - The member who invested
 * @param {number} investment - The invested amount
 */
async function triggerDirectAndLevelBonus(memberId, investment) {
  const rates = await getCommissionRates()

  const current = await prisma.user.findUnique({ 
    where: { id: memberId },
    select: { sponsor_id: true, user_id: true }
  })
  if (!current?.sponsor_id) return

  const sponsorId = current.sponsor_id
  
  // Check if sponsor is active
  const sponsor = await prisma.user.findUnique({ 
    where: { id: sponsorId },
    select: { status: true }
  })

  if (sponsor?.status === 'active') {
    const directBonusAmt = parseFloat((investment * rates.direct / 100).toFixed(2))
    if (directBonusAmt > 0) {
      await prisma.$transaction(async (tx) => {
        await creditBonus(
          tx,
          sponsorId,
          directBonusAmt,
          'direct',
          memberId,
          1,
          `Direct referral bonus from ${current.user_id}`
        )
      })
    }
  }
}

/**
 * Trigger 15-level ROI matching bonus based on daily ROI generated by the downline.
 * @param {PrismaClient} tx
 * @param {number} memberId
 * @param {string} memberUserId
 * @param {number} roiAmount
 */
async function triggerROIMatchingBonus(tx, memberId, memberUserId, roiAmount) {
  const LEVEL_RATES = [0, 20, 15, 10, 5, 4, 3, 2, 2, 2, 1, 1, 1, 1, 0.5, 0.5]
  
  let currentId = memberId
  let level = 1

  while (level <= 15) {
    const current = await tx.user.findUnique({ 
      where: { id: currentId },
      select: { sponsor_id: true }
    })
    if (!current?.sponsor_id) break

    const sponsorId = current.sponsor_id
    
    const sponsor = await tx.user.findUnique({ 
      where: { id: sponsorId },
      select: { status: true }
    })

    if (sponsor?.status === 'active') {
      const directActives = await tx.user.count({
        where: { sponsor_id: sponsorId, status: 'active' }
      })

      if (directActives >= level) {
        const rate = LEVEL_RATES[level] || 0
        const bonusAmt = parseFloat((roiAmount * rate / 100).toFixed(2))
        if (bonusAmt > 0) {
          await creditBonus(
            tx,
            sponsorId,
            bonusAmt,
            'level',
            memberId,
            level,
            `Level ${level} ROI matching bonus from ${memberUserId}`
          )
        }
      }
    }

    currentId = sponsorId
    level++
  }
}

module.exports = { triggerDirectAndLevelBonus, triggerROIMatchingBonus }
