/**
 * Bonus Engine
 * Handles direct referral bonus + 15-level ROI matching commission.
 *
 * Rules:
 * - Direct Referral Bonus: 5% of package amount, paid on activation.
 *   Sponsor must be active AND have at least one active trade package.
 * - ROI Matching Bonus: 15-level % of daily ROI, paid daily via cron.
 *   Each level's sponsor must be active AND have at least one active trade package.
 */

const prisma = require('../lib/prisma')

// Default commission rates
const DEFAULT_RATES = {
  direct: 5.0,
  levels: [0, 20, 15, 10, 5, 4, 3, 2, 2, 2, 1, 1, 1, 1, 0.5, 0.5], // index = level
}

async function getCommissionRates() {
  try {
    const [levelsSetting, directSetting] = await Promise.all([
      prisma.setting.findUnique({ where: { key: 'level_bonus_rates' } }),
      prisma.setting.findUnique({ where: { key: 'direct_bonus_pct' } })
    ])
    return {
      direct: directSetting ? parseFloat(directSetting.value) : DEFAULT_RATES.direct,
      levels: levelsSetting ? JSON.parse(levelsSetting.value) : DEFAULT_RATES.levels,
    }
  } catch {
    return DEFAULT_RATES
  }
}

/**
 * Credit a bonus to a user's income wallet and create ledger entry.
 * NOTE: This is called OUTSIDE a transaction for the ROI matching bonus
 * to avoid long-running transaction locks.
 *
 * @param {PrismaClient} client  - Prisma client (tx or global)
 * @param {number} userId
 * @param {number} amount
 * @param {string} bonusType - 'direct' | 'level' | 'trading'
 * @param {number} fromUserId
 * @param {number} level
 * @param {string} remarks
 */
async function creditBonus(client, userId, amount, bonusType, fromUserId, level, remarks) {
  if (amount <= 0) return

  const updated = await client.user.update({
    where: { id: userId },
    data:  { income_wallet_balance: { increment: amount } },
  })

  await Promise.all([
    client.bonus.create({
      data: {
        user_id:      userId,
        from_user_id: fromUserId,
        type:         bonusType,
        level,
        amount,
      },
    }),
    client.incomeLedger.create({
      data: {
        user_id:        userId,
        type:           'credit',
        amount,
        balance_after:  updated.income_wallet_balance,
        remarks,
        reference_type: 'bonus',
      },
    }),
  ])
}

/**
 * Check whether a user has at least one active trade package.
 * Used to qualify a sponsor for direct or level bonus.
 */
async function hasActivePackage(userId) {
  const pkg = await prisma.tradePackage.findFirst({
    where: { user_id: userId, status: 'active' },
    select: { id: true }
  })
  return pkg !== null
}

/**
 * Trigger direct referral bonus (5%) when a member activates a trade package.
 * Conditions:
 *  - Sponsor must have status === 'active'
 *  - Sponsor must have at least one active trade package
 *
 * @param {number} memberId   - The member who invested
 * @param {number} investment - The invested amount
 */
async function triggerDirectAndLevelBonus(memberId, investment) {
  const rates = await getCommissionRates()

  const current = await prisma.user.findUnique({ 
    where: { id: memberId },
    select: { sponsor_id: true, user_id: true }
  })
  if (!current?.sponsor_id) return

  const sponsorId = current.sponsor_id
  
  // Check if sponsor is active
  const sponsor = await prisma.user.findUnique({ 
    where: { id: sponsorId },
    select: { status: true }
  })

  // Direct referral bonus: sponsor only needs to be active — no own package required.
  // hasActivePackage gate applies only to ROI level matching bonus (triggerROIMatchingBonus).
  if (sponsor?.status === 'active') {
    const directBonusAmt = parseFloat((investment * rates.direct / 100).toFixed(2))
    if (directBonusAmt > 0) {
      await prisma.$transaction(async (tx) => {
        await creditBonus(
          tx,
          sponsorId,
          directBonusAmt,
          'direct',
          memberId,
          1,
          `Direct referral bonus from ${current.user_id}`
        )
      })
    }
  }
}

/**
 * Trigger 15-level ROI matching bonus based on daily ROI generated by the downline.
 *
 * FIX #3: This function now runs OUTSIDE the main ROI transaction to prevent
 * long-running transaction locks and Vercel timeout issues.
 * It uses the global `prisma` client (not `tx`) for independent, non-blocking execution.
 *
 * FIX #5: Each level sponsor must be active AND have an active trade package.
 *
 * @param {number} memberId      - The member who generated ROI
 * @param {string} memberUserId  - Display ID for ledger remarks
 * @param {number} roiAmount     - The ROI amount generated
 */
async function triggerROIMatchingBonus(memberId, memberUserId, roiAmount) {
  const rates = await getCommissionRates()
  const LEVEL_RATES = rates.levels

  let currentId = memberId
  let level = 1

  // Walk up the sponsor chain up to 15 levels
  while (level <= 15) {
    const current = await prisma.user.findUnique({
      where:  { id: currentId },
      select: { sponsor_id: true },
    })
    if (!current?.sponsor_id) break

    const sponsorId = current.sponsor_id

    const sponsor = await prisma.user.findUnique({
      where:  { id: sponsorId },
      select: { status: true },
    })

    // Sponsor must be active AND have at least one active trade package
    if (sponsor?.status === 'active' && await hasActivePackage(sponsorId)) {
      // Count direct referrals of this sponsor who have at least one active trade package.
      // Using User.count with packages.some is the stable Prisma pattern — avoids unreliable
      // nested relation filters on count(), and correctly counts unique investors (not packages).
      const activeDownlineCount = await prisma.user.count({
        where: {
          sponsor_id: sponsorId,
          packages:   { some: { status: 'active' } },
        },
      })

      // Gate: sponsor must have at least `level` active investing referrals to earn at this depth
      if (activeDownlineCount >= level) {
        const rate     = LEVEL_RATES[level] || 0
        const bonusAmt = parseFloat((roiAmount * rate / 100).toFixed(2))
        if (bonusAmt > 0) {
          // Each bonus credit is its own small atomic transaction — avoids giant lock
          await prisma.$transaction(async (tx) => {
            await creditBonus(
              tx,
              sponsorId,
              bonusAmt,
              'level',
              memberId,
              level,
              `Level ${level} ROI matching bonus from ${memberUserId}`,
            )
          })
        }
      }
    }

    currentId = sponsorId
    level++
  }
}

module.exports = { triggerDirectAndLevelBonus, triggerROIMatchingBonus }
